### ISSUE TITLE
missing requirements

### ISSUE THREAD

**Issue by dribnet** [dribnet/clipit#1]
It's known that the repo is sloppy with requirements, in particular it needs pip install of:

braceexpand
perlin_numpy

This issue replaces dribnet/clipit_old#3 (more context there)

**Comment by dribnet** [comment]
Marking this as help wanted. If someone would like the requirements to work, please help and post a MR.

**Comment by aranair** [comment]
I think scikit-image (skimage) as well? (w/o it, the pixeldrawer import fails)

**Comment by Wheest** [comment]
I had import errors with pydiffvg, I have made a [PR](https://github.com/dribnet/clipit/pull/13) which fixes this for the PixelDrawer notebook.

The top level error was `NameError: name 'PixelDrawer' is not defined.`, see the PR for how I debugged it.

**Comment by dribnet** [comment]
Thanks for pointing out these issues. I have recently moved the core library to the [pixray]( https://github.com/dribnet/pixray) repo and will followup there. It's a bit tricky because it is possible to run some models (like vqgan) without diffvg and its dependencies (like skimage). But it would probably be good at least to offer a requirements or setup.py file that covered all the bases.

**Comment by dribnet** [comment]
don't mind me, just dropping off some files.

[shoetable.zip](https://github.com/dribnet/clipit/files/7256353/shoetable.zip)

**Comment by boardmain** [comment]
> I had import errors with pydiffvg, I have made a [PR](https://github.com/dribnet/clipit/pull/13) which fixes this for the PixelDrawer notebook.
> 
> The top level error was `NameError: name 'PixelDrawer' is not defined.`, see the PR for how I debugged it.

same error, how you solved?

**Comment by dribnet** [comment]
> > I had import errors with pydiffvg, I have made a [PR](https://github.com/dribnet/clipit/pull/13) which fixes this for the PixelDrawer notebook.
> > The top level error was `NameError: name 'PixelDrawer' is not defined.`, see the PR for how I debugged it.
> 
> same error, how you solved?

Is this using the notebook? Did you run the setup cell and then "restart runtime"?

The error is a symptom that diffvg is not installed, but running setup and restarting the runtime is supposed to fix this.

**Comment by boardmain** [comment]
> > > I had import errors with pydiffvg, I have made a [PR](https://github.com/dribnet/clipit/pull/13) which fixes this for the PixelDrawer notebook.
> > > The top level error was `NameError: name 'PixelDrawer' is not defined.`, see the PR for how I debugged it.
> > 
> > 
> > same error, how you solved?
> 
> Is this using the notebook? Did you run the setup cell and then "restart runtime"?
> 
> The error is a symptom that diffvg is not installed, but running setup and restarting the runtime is supposed to fix this.

yes im running from macos
diffvg installed en restarted runtime
but same error


EDIT

solved scikit-image was missing ( used in pixeldrawer.py)
