### ISSUE TITLE
RuntimeError: Sizes of tensors

### ISSUE THREAD

**Issue by z3Nsk1Fh5a** [dribnet/clipit#12]
`Using device: cuda:0
Optimising using: AdamP
Using text prompts: ['leaf:-2', 'area:-3', 'flatness:5', 'text:-2', 'light on silver:3', 'flat Art', 'iridescence:1', 'the light and metallic volume of color luminance displayed']
Using seed: -1
Oops: runtime error:  Sizes of tensors must match except in dimension 3. Got 224 and 398 (The offending index is 0)
Try reducing --num-cuts to save memory
/usr/local/lib/python3.7/dist-packages/torch/nn/functional.py:3613: UserWarning: Default upsampling behavior when mode=bilinear is changed to align_corners=False since 0.4.0. Please specify align_corners=True if the old behavior is desired. See the documentation of nn.Upsample for details.
  "See the documentation of nn.Upsample for details.".format(mode)`
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-18-c0cf72a5f4a4> in <module>()
    104 settings = clipit.apply_settings()
    105 clipit.do_init(settings)
--> 106 clipit.do_run(settings)

5 frames
/content/clipit/clipit.py in forward(self, input, spot)
    338             batch2, transforms2 = self.augs_wide(torch.cat(cutouts[self.cutn_zoom:], dim=0))
    339             # print(batch1.shape, batch2.shape)
--> 340             batch = torch.cat([batch1, batch2])
    341             # print(batch.shape)
    342             self.transforms = torch.cat([transforms1, transforms2])

RuntimeError: Sizes of tensors must match except in dimension 3. Got 224 and 398 (The offending index is 0)`

**Comment by dribnet** [comment]
what notebook and settings?

**Comment by dribnet** [comment]
Fixed in #8
