### ISSUE TITLE
Pixel Size

### ISSUE THREAD

**Issue by z3Nsk1Fh5a** [dribnet/clipit#8]
What are recommended params for pixel_size?  I am trying to achieve smaller pixels; have tried 1,1 - 2,2 - 3,3 - 8,8 - 16,16

Am I doing it incorrectly?  Probably.  I tried via direct adding pixel_size = [4, 4] as well as `clipit.add_settings(pixel_size = [16, 16])`. without any change in visual output.

**Comment by dribnet** [comment]
I have recently added an easier setting to use: `pixel_scale`. To make the pixels twice as big, simply add this line:

```python
clipit.add_settings(pixel_scale=2)
```

![sunset1](https://user-images.githubusercontent.com/945979/131152443-353a87a5-6632-4014-9642-14236aed6f16.png)

Note `pixel_scale` can also be a fraction. So to make the pixels smaller (and get *more* pixels) instead try:

```python
clipit.add_settings(pixel_scale=0.75)
```

![scene2](https://user-images.githubusercontent.com/945979/131153329-cf921a66-03e5-4321-81e5-68a4244e1f5e.png)

Settings can be applied in any order, just make sure to call `add_settings` anytime before the settings are finalised by `apply_settings`:

```python
# establish the settings for the run after all calls to add_settings()
settings = clipit.apply_settings()
```

**Comment by z3Nsk1Fh5a** [comment]
I tried `clipit.add_settings(size = 200, 500)` as well as `(size = [200,500])` and it outputs the same dimensions always.

**Comment by dribnet** [comment]
The setting I recommend is `pixel_scale`

```
clipit.add_settings(pixel_scale=2)
```

You can instead try `pixel_size` but then you have to be careful to also adjust `size` to have a matching aspect ratio (unless you are wanting non-square pixels).

**Comment by z3Nsk1Fh5a** [comment]
pixel scale is working fantastic for making the image resolution change and change the size of the the pixels.  I am sort of trying to achieve a slender tall image like a tree, so I am thinking how to go about this.  Changing the size for a tall and skinny or exceptionally thin and wide cut of image must be possible but I am a noob with code.

**Comment by dribnet** [comment]
Thanks - I hadn't made many tall images and it turns out there was a bug in that processing. But I have just patched it.

The key is to change the size and pixel_size and to make sure that the ratios match so you get square pixels. So for example:

```python
clipit.add_settings(size=[128, 512], pixel_size[32, 128], prompt='The Tallest Tree in the Forest by Shel Silverstein #pixelart')
```
![tall_tree_02](https://user-images.githubusercontent.com/945979/132093038-b3694ed8-9ae4-4117-accb-84e52abb4630.png)

Or conversely

```python
clipit.add_settings(size=[512, 128], pixel_size[128, 32], prompt='The Widest Tree in the Forest by Shel Silverstein #pixelart')
```

![tall_tree_03](https://user-images.githubusercontent.com/945979/132093073-f5683de3-bda0-4ec6-8b83-f48218580e95.png)

And for those using the command line - here are the commands for those two.
```bash
python clipit.py \
  --quality better \
  --use_pixeldraw True \
  --size 128 512  \
  --pixel_size 32 128 \
  --prompt 'The Tallest Tree in the Forest by Shel Silverstein #pixelart' \
  --output tall_tree.png

python clipit.py \
  --quality better \
  --use_pixeldraw True \
  --size 512 128 \
  --pixel_size 128 32 \
  --prompt 'The Widest Tree in the Forest by Shel Silverstein #pixelart' \
  --output wide_tree.png
```
